### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by Stubborn-z** [stanford-oval/storm#112] opened 2024-07-30 00:37 UTC
Thank you very much for your contribution! I encountered the same problem as [#14 ](https://github.com/stanford-oval/storm/issues/14)when running the command
```shell
-- python -m scripts.run_writing --input-source console --input-path ../FreshWiki/topic_list.csv --engine gpt-4 --do-polish-article --remove-duplicate. 
```
The error is
```shell
ValueError: Expected 2D array, got 1D array instead: array=[]. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample. 
```
Then I checked what you said a bunch of  
```shell 
root : ERROR : Error occurs when searching query xxx: 'hits'?
``` 
and found that mine is 
```shell
Error occurs when searching query Taylor Hawkins musical influences: 'url' 
Error occurs when searching query Taylor Hawkins musical background: 'url'
Error occurs when searching query Music inspirations of Taylor Hawkins: 'url'
...
...
```  
Can you help me check it?

**Comment by Yucheng-Jiang** [comment] 2024-07-31 17:50
This issue occurs mostly likely due to mis-configuration of retriever (e.g. You.com API call failure, network issues, etc.) that result in no information is retrieved. Refer to [this comment](https://github.com/stanford-oval/storm/issues/14#issuecomment-2060500498).

**Comment by Yucheng-Jiang** [comment] 2024-07-31 18:25
Close this issue as duplicate of #62

**Closed by Yucheng-Jiang** 2024-07-31 18:25 UTC
Labels: Bug Report - User Environment
