### ISSUE TITLE
Error issued by display_article_page() in Streamlit interface

### ISSUE THREAD

**Issue by ibagur** [stanford-oval/storm#89] opened 2024-07-18 21:28 UTC
## Description
When attempting to select an existing generated article from the Streamlit interface in the MyArticles page, an error is issued in the streamlit interface and also the following error appears in the terminal_

```
...
demo_util.display_article_page(selected_article_name=selected_article_name,
TypeError: display_article_page() got an unexpected keyword argument 'show_feedback_form'
```

## Steps to Reproduce
1. Open the STORM Streamlit interface
2. Go to the "My Articles" page
3. Try to select an existing generated article

## Expected Behavior
The selected article should be displayed without any errors.

## Actual Behavior
The application throws a TypeError, indicating that the `display_article_page()` function received an unexpected keyword argument 'show_feedback_form'.

## Root Cause
The `my_articles_page()` function in `MyArticles.py` was calling `demo_util.display_article_page()` with parameters that are not defined in the function signature in `demo_util.py`.

## Fix
The issue has been resolved by removing the unexpected parameters `show_feedback_form` and `show_qa_panel` from the `display_article_page()` function call in the `MyArticles.py` file.

In the file `./storm/frontend/demo_light/pages_util/MyArticles.py`, the following change was made:

```python
# Before
demo_util.display_article_page(selected_article_name=selected_article_name,
selected_article_file_path_dict=selected_article_file_path_dict,
show_title=True, show_main_article=True,
show_feedback_form=False,
show_qa_panel=False)

# After
demo_util.display_article_page(selected_article_name=selected_article_name,
selected_article_file_path_dict=selected_article_file_path_dict,
show_title=True, show_main_article=True)
```

## Environment
- Operating System: macOS Sonoma
- Python version: 3.11
- STORM tool version: latest release

**Comment by shawng00din** [comment] 2024-07-23 19:54
I got an error here and had to add these two parameters back into demo_util.display_article_page
show_feedback_form=False,
show_qa_panel=False)

#Environment
Operating System: macOS Ventura 13.4
Chip Apple M2
Python version: 3.11
STORM tool version: latest release

**Comment by MrEdwards007** [comment] 2024-07-28 22:50
I am running STORM locally and encountered the error.  I've confirmed, the solution provided by @ibagur works.
OS: Ubuntu 22.04.4 LTS
Python version: 3.11
STORM tool version: latest release

**Comment by Yucheng-Jiang** [comment] 2024-08-01 19:33
Thanks for catching this. The issue is resolved in [recent PR](https://github.com/stanford-oval/storm/pull/118). Last main branch should have a working version of demo light.

**Closed by Yucheng-Jiang** 2024-08-01 19:33 UTC
