### ISSUE TITLE
Issue: STORM's Article Length Limitation (Revised)

### ISSUE THREAD

**Issue by mohamedfadlalla** [stanford-oval/storm#152] opened 2024-08-28 21:50 UTC
Problem: Despite increasing the maximum token limit of the model, STORM continues to produce articles of limited length, typically around 7 pages. Additionally, increasing the following parameters to 5 from their default values of 3 has not yielded significant improvements:

--max-conv-turn:5
--max-perspective:5
--search-top-k:5
--retrieve-top-k:5
Desired Outcome: The ability to generate articles of significantly greater length, ideally aiming for 50 pages or more.

How can I increase the output length and make it more verbose and explanatory?

**Comment by Yucheng-Jiang** [comment] 2024-08-31 11:00
Close as duplicate of #154

**Closed by Yucheng-Jiang** 2024-08-31 11:00 UTC
