### ISSUE TITLE
[BUG] Website broken

### ISSUE THREAD

**Issue by mihailpettas** [stanford-oval/storm#172] opened 2024-09-18 16:09 UTC
**Describe the bug**
Both buttons in website just reload it

**Environment:**
 - OS: Windows
 - Browser [e.g. chrome, safari] Chrome/Edge

**Comment by shaoyijia** [comment] 2024-09-23 05:23
Recently, the web research preview is not stable due to a surge of usage. We are trying to improve its concurrent capacity.
Close this issue since it is not a bug with the this codebase.

**Closed by shaoyijia** 2024-09-23 05:23 UTC
